const defaultData = {
  type: 'Stock light freighter',
  craft: 'Corellian Engineering Corporation YT-1300 Transport',
  scale: 'Starfighter',
  cargoCapacity: '100 metric tons',
  consumables: '2 months',
  _totalCrew: 100,
  crew_notes: '',
  crew_1_label: 'Normal crew',
  crew_1_value_1: 1,
  crew_1_notes: '1 can coordinate',
  crew_2_label: 'Gunners',
  crew_2_value_1: 1,
  crew_3_label: 'Passengers',
  crew_3_value_1: 6,
  hasNavComputer: true,
  navComputer_notes: '',
  speed_space: 4,
  speed_atmosphere: 480,
  maneuverability: '2D',
  hyperdrive: 'x2',
  hyperdrive_notes: 'Hyperdrive allow spaceship to navigate through hyperspace.',
  hyperdrive_1_label: 'Hyperdrive Backup',
  hyperdrive_1_value_1: 'x12',
  shields: '2D',
  shields_notes: '',
  hull: '4D',
  hull_notes: '',
  sensors_notes: '',
  sensors_1_label: 'Passive',
  sensors_1_value_1: 10,
  sensors_1_value_2: '0D',
  sensors_2_label: 'Scan',
  sensors_2_value_1: 25,
  sensors_2_value_2: '1D',
  sensors_3_label: 'Search',
  sensors_3_value_1: 40,
  sensors_3_value_2: '2D',
  sensors_4_label: 'Focus',
  sensors_4_value_1: 2,
  sensors_4_value_2: '3D',
  weapon_1_name: 'Laser Cannon',
  weapon_1_type: 'Laser Cannon',
  weapon_1_fireLinked: false,
  weapon_1_notes: '',
  weapon_1_fireControl: '2D',
  weapon_1_damage: '4D',
  weapon_1_sub_1_label: 'Crew',
  weapon_1_sub_1_value_1: 1,
  weapon_1_sub_1_notes: '',
  weapon_1_sub_2_label: 'Range',
  weapon_1_sub_2_value_1: 1,
  weapon_1_sub_2_value_2: 3,
  weapon_1_sub_2_value_3: 12,
  weapon_1_sub_2_value_4: 25,
  weapon_1_sub_2_notes: '',
};