const defaultData = {
  type: 'Stock light freighter',
  craft: 'Corellian Engineering Corporation YT-1300 Transport',
  scale: 'Starfighter',
  cargoCapacity: '100 metric tons',
  consumables: '2 months',
  _totalCrew: 100,
  crew_notes: '',
  crew_1_label: 'Normal crew',
  crew_1_value_1: 1,
  crew_1_notes: '1 can coordinate',
  crew_2_label: 'Gunners',
  crew_2_value_1: 1,
  crew_3_label: 'Passengers',
  crew_3_value_1: 6,
  shields: '2D',
  shields_notes: '',
  hull: '4D',
  hull_notes: '',
  sensors_notes: '',
  sensors_focus: '2 / 3D',
  weapon_1_name: 'Laser Cannon',
  weapon_1_type: 'Laser Cannon',
  weapon_1_fireLinked: false,
  weapon_1_notes: '',
  weapon_1_fireControl: '2D',
  weapon_1_damage: '4D',
  weapon_1_sub_1_label: 'Crew',
  weapon_1_sub_1_value_1: 1,
  weapon_1_sub_1_notes: '',
  weapon_1_sub_2_label: 'Range',
  weapon_1_sub_2_value_1: 1,
  weapon_1_sub_2_value_2: 3,
  weapon_1_sub_2_value_3: 12,
  weapon_1_sub_2_value_4: 25,
  weapon_1_sub_2_notes: '',
};